application: tghwputty
version: 1
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: "365d"

inbound_services:
- mail
- channel_presence
- warmup

handlers:

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  mime_type: image/x-icon

- url: /respond-proxy\.html
  static_files: static/respond/respond-proxy.html
  upload: static/respond/respond-proxy\.html

- url: /static/img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))

- url: /static/img/docs/(.*\.(gif|png|jpg))
  static_files: static/img/docs/\1
  upload: static/img/docs/(.*\.(gif|png|jpg))

- url: /static/css/(.*\.css)
  mime_type: text/css
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /static/js/(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /static/codemirror/(.*\.css)
  mime_type: text/css
  static_files: static/codemirror/\1
  upload: static/codemirror/(.*\.css)

- url: /static/codemirror/(.*\.js)
  mime_type: text/javascript
  static_files: static/codemirror/\1
  upload: static/codemirror/(.*\.js)

- url: /_ah/mail/.+
  script: incoming_email_handler.application
  login: admin

- url: /_migrate
  script: bootstrap.app
  login: admin

- url: /gae_mini_profiler/static/js/(.*\.tmpl)
  mime_type: text/html
  static_files: libs/gae_mini_profiler/static/js/\1
  upload: libs/gae_mini_profiler/static/js/(.*\.tmpl)

- url: /gae_mini_profiler/static
  static_dir: libs/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: libs.gae_mini_profiler.main.app

- url: /livecount/counter_admin
  script: libs.livecount.counter_admin.application
  login: admin

- url: /livecount/.*
  script: libs.livecount.counter.application
  login: admin

- url: /tasks/.*
  script: bootstrap.app
  login: admin

- url: .*\.(jpg|gif|png)
  static_files: static/img/404.png
  upload: static/img/404.png

- url: .*
  script: bootstrap.app

